### ISSUE TITLE
1.13 compatibility

### ISSUE THREAD

**Issue by k-jiang** [ezeiger92/Prism-Bukkit#5]
I used some BONE_MEAL to grow a crop. After I typed a lookup command Prism generates this exception:
```
>pr l w:world
[11:30:05 WARN]: [Prism] Plugin Prism v2.1.0-${env.BUILD_NUMBER} generated an exception while executing task 2902
java.lang.IllegalArgumentException: Cannot get data for not block BONE_MEAL
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191) ~[spigot-1.13-latest.jar:git-Spigot-69774b3-5e3082c]
	at org.bukkit.craftbukkit.v1_13_R1.block.data.CraftBlockData.newData(CraftBlockData.java:420) ~[spigot-1.13-latest.jar:git-Spigot-69774b3-5e3082c]
	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.createBlockData(CraftServer.java:1808) ~[spigot-1.13-latest.jar:git-Spigot-69774b3-5e3082c]
	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.createBlockData(CraftServer.java:1783) ~[spigot-1.13-latest.jar:git-Spigot-69774b3-5e3082c]
	at org.bukkit.Bukkit.createBlockData(Bukkit.java:1185) ~[spigot-1.13-latest.jar:git-Spigot-69774b3-5e3082c]
	at me.botsko.prism.actionlibs.ActionsQuery.lookup(ActionsQuery.java:189) ~[?:?]
	at me.botsko.prism.commands.LookupCommand$1.run(LookupCommand.java:69) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.13-latest.jar:git-Spigot-69774b3-5e3082c]
	at org.bukkit.craftbukkit.v1_13_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.13-latest.jar:git-Spigot-69774b3-5e3082c]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```

p.s. Thank you for contributing to this project! So far Prism-Bukkit is the best recording/rollback plugin I have ever found and my server could not lived without it.

**Comment by ezeiger92** [comment]
I'm seeing that as well, give me a few minutes.
