### ISSUE TITLE
Prism inspector wand enable

### ISSUE THREAD

**Issue by Tjird** [ezeiger92/Prism-Bukkit#6]
When I am trying to enable inspector mode I get this error log

[21:59:13 INFO]: Tjird issued server command: /prism i
[21:59:13 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'prism' in plugin Prism v2.1.0-${env.BUILD_NUMBER}
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Paper-1501]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[spigot.jar:git-Paper-1501]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685) ~[spigot.jar:git-Paper-1501]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1473) ~[spigot.jar:git-Paper-1501]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1278) ~[spigot.jar:git-Paper-1501]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot.jar:git-Paper-1501]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[spigot.jar:git-Paper-1501]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[spigot.jar:git-Paper-1501]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_181]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_181]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Paper-1501]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:849) [spigot.jar:git-Paper-1501]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [spigot.jar:git-Paper-1501]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:773) [spigot.jar:git-Paper-1501]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [spigot.jar:git-Paper-1501]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:98) ~[spigot.jar:git-Paper-1501]
        at me.botsko.prism.commands.WandCommand.handle(WandCommand.java:229) ~[?:?]
        at me.botsko.prism.commandlibs.Executor.onCommand(Executor.java:104) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Paper-1501]
        ... 15 more

Prism 1.12 PaperSpigot 1.12.2

**Comment by ezeiger92** [comment]
The config option `prism.wands.default-item-mode-id` is probably still `280:0`, change this to a material name like `stick`. Same applies to other item ids in the config.

**Comment by Tjird** [comment]
I am checking, give me a sec.

**Comment by Tjird** [comment]
Still not working, BUT if I set by myself an item then it works.
I can't inspect with my hand (empty slot), then I am getting also an internal error.

If I inspect a worldedited part I only get to what it is edited not the previous block.

**Comment by Tjird** [comment]
If you need more information about the issues in my last comment, hit me up ;).

**Comment by ezeiger92** [comment]
Hate to do this here too, but I'm only supporting the latest version, not 1.12.2. That and I haven't even made a beta build for any version yet.

**Comment by Tjird** [comment]
Sorry, I thought you only focus on the latest version for new features and fix bugs for all of your made versions. Misunderstanding on my side there.
